set mode MySQL;

CREATE SCHEMA Events;

CREATE MEMORY TABLE Events.Status( 
IDENTIFIER	VARCHAR(255) PRIMARY KEY,
NODE		VARCHAR(64) NOT NULL,
NODEALIAS	VARCHAR(64),
ALERTGROUP	VARCHAR(255),
ALERTKEY	VARCHAR(255),
SEVERITY	INT,
SUMMARY		VARCHAR(1000) NOT NULL,
STATECHANGE	TIMESTAMP WITH TIME ZONE NOT NULL,
FIRSTOCCURRENCE	TIMESTAMP WITH TIME ZONE NOT NULL,
LASTOCCURRENCE	TIMESTAMP WITH TIME ZONE NOT NULL,
TYPE		INT,
TALLY		INT
);

CREATE VIEW EVENTS.STATUS_VIEW AS SELECT * FROM EVENTS.STATUS;

CREATE TRIGGER STATUSCHANGE
INSTEAD OF INSERT,UPDATE,DELETE ON EVENTS.STATUS_VIEW FOR EACH ROW 
CALL "org.conyevents.triggers.StatusChange";

--CREATE TRIGGER NewEvent
--BEFORE INSERT ON EVENTS.STATUS FOR EACH ROW 
--CALL "org.conyevents.triggers.NewEvent";


--CREATE TRIGGER EVENTCHANGE
--INSTEAD OF INSERT,UPDATE ON EVENTS.STATUS FOR EACH ROW 
--CALL "org.conyevents.triggers.EventChange";

